site_name: My Docs
nav: 
- Home: 'index.md'
- Phishing Campaigns: 
  - GoPhish: 'phishing/guide.md'
  - Phishing Templates: 'phishing/templates.md'
- Disinformation:
  - Steves Paper: 'disinformation/paper.md'
theme: ivory

